export enum TransactionEventEnums {
  SEND_TRANSACTION_CONFIRMATION_CODE = 'SEND_TRANSACTION_CONFIRMATION_CODE',
  PAYMENT_LINK_CONFIRMATION_MAIL = 'PAYMENT_LINK_CONFIRMATION_MAIL',
  WITHDRAWAL_CONFIRMATION_MAIL = 'WITHDRAWAL_CONFIRMATION_MAIL',
}
