export enum AuthenticationEventEnums {
  EMAIL_VERIFICATION_EMAIL_OTP = 'EMAIL_VERIFICATION_EMAIL_OTP',
  RESEND_EMAIL_VERIFICATION_OTP = 'RESEND_EMAIL_VERIFICATION_OTP',
  SEND_WELCOME_EMAIL = 'SEND_WELCOME_EMAIL',
  SEND_PASSWORD_RESET_EMAIL = 'SEND_PASSWORD_RESET_EMAIL',
  NEW_BUSINESS_ACCOUNT = 'NEW_BUSINESS_ACCOUNT',
  LOGIN_ALERT = 'LOGIN_ALERT',
  SAVE_LOGGED_IN_DEVICE = 'SAVE_LOGGED_IN_DEVICE',
  LOGIN_ACTIVITY_LOG = 'LOGIN_ACTIVITY_LOG',
}
