name: nookvest-deploy
on:
  push:
    branches:
      - dev

jobs:
  build_and_push:

    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: clockchain/backendartifacts

  deploy:
      runs-on: ubuntu-latest
      needs: build_and_push
      
      steps:
        - name: Deploy to Digital Ocean droplet via SSH action
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSHKEY }}
            script: |
              sudo ./deploy.sh