export enum BusinessEventsEnum {
  SUCCESSFUL_REGISTRATION_NOTIFICATION = 'SUCCESSFUL_REGISTRATION_NOTIFICATION',
  EMAIl_CONFIRMATION_OPT = 'EMAIl_CONFIRMATION_OPT',
  PASSWORD_RESET_OTP = 'PASSWORD_RESET_OTP',
  ACCOUNT_INVITE_MAIL = 'ACCOUNT_INVITE_MAIL',
  NEW_BUSINESS_ACCOUNT = 'NEW_BUSINESS_ACCOUNT',
  BUSINESS_MEMBER_ACTIVITY = 'BUSINESS_MEMBER_ACTIVITY',
  KYC_VERIFICATION = 'KYC_VERIFICATION',
  KYB_VERIFICATION = 'KYB_VERIFICATION',
}
