runtime: nodejs18

instance_class: F4

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 3

entrypoint: npm run start

handlers:
  - url: /_next/static
    static_dir: .next/static

  - url: /_next/.*
    script: auto

  - url: /.*
    script: auto

env_variables:
  NODE_ENV: 'production'
  POSTGRES_DB_HOST: 143.244.200.133
  POSTGRES_DB_USER: clockserveradmin
  POSTGRES_DB_PASSWORD: 1YWj4EhYM1we
  POSTGRES_DB_NAME: clockchaindb
  POSTGRES_DB_PORT: 5432
  PORT: 3245
  TOKEN_EXPIRATION_TIME: '1d'
  TOKEN_SECRET: 'developmentdevelopment'
  REFRESH_TOKEN_EXPIRATION_TIME: '1d'
  TERMII_API_KEY: 'TLntvebddRXVI7n2kOQgc0aCHrYid8H2B0wvMJMplT9YnjhNRP65fZeDq3Gkrv'
  SERVER_URL: 'http://localhost:3500/api/v1'
  THROTTLE_LIMIT: '60'
  THROTTLE_TTL: '3'
  CLOUDINARY_API_KEY: '327183992636358'
  CLOUDINARY_API_SECRET: 'Q7ecN1eihe3-n3xGjsjO_t4Fh0A'
  CLOUDINARY_NAME: 'dlbjdsad5'
  DOJAH_SECRET_KEY: 'prod_sk_Y4PfCqw2I9vacne2X6FvQzdFT'
  DOJAH_APP_ID: '65011fd04143c30040c90a35'
  FLUTTER_WAVE_SECRET_KEY: 'FLWSECK_TEST-970c7f0c0e5954b3de647a2a4c1bc047-X'
  FLUTTER_WAVE_ENCRYPTION_SECRET: 'FLWSECK_TEST2d28f643f5c0'
  MAIL_GUN_SECRET_KEY: '9f2a8539f8affa3bb7bf32154a4524b8-2c441066-439609b8'
  ADMIN_DASHBOARD_URL: 'https://cpay-admin-frontend.vercel.app'
  FRONTEND_URL: 'https://cpay.theclockchain.io'
  FIRE_BLOCK_API_SANDBOX_KEY: '011d8643-47de-414f-8b24-a63cc140d76e'
  FIRE_BLOCK_API_LIVE_KEY: '011d8643-47de-414f-8b24-a63cc140d76e'
  FIRE_BLOCK_PUB_KEY: 'xpub661MyMwAqRbcF1hc5MX7n3qaiM6tB5hRtkEYgRzW9dMNd78esVCeWqckWAM93663vEFwmCQxNqDXBgorZEzXkK6vPBudgP9w61KGvKZRnnm'
  FIRE_BLOCK_BASE_URL: 'https://sandbox-api.fireblocks.io'
  API_ENCRYPT_AND_DECRYPT_KEY: 'd6az9303655f3sa2af2a56202961c015'
  FIRE_BLOCK_API_SECRET: 'd6az9303655f3sa2af2a56202961c015'
  IDENTITYPASS_SEC_KEY: 'live_sk_vKyI52CVHwNQxZqG2bl5csIHOEnk01EWLycrAWj'
  IDENTITYPASS_APP_ID: '329b05f8-5b11-4a1e-9dd2-3706a2adbf95'
  TRONSCAN_API_KEY_TOKEN: '61186061-d4d0-4a14-9990-d9508755485a'
  OPTIMISM_SEC_KEY: 'FSZ4QEBGF1RCZFU1FYJ7K2U233U7Y6GIU2'
  ETHER_SCAN_KEY: 'T2RFK16WNGWWJ3XJQA7SW91WF8RRY1BS3I'
  POLYGON_SCAN_KEY: 'C53SD8E3ANM4M6SSACYVR2V6G2NF76MVXQ'
  BSC_SCAN_KEY: '1P7H8G5ZRA2ZF4MY8CIUQA7DHBG6CSNR7G'
  SOL_SCAN_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkQXQiOjE3MTY2MjgwMTYwMjcsImVtYWlsIjoiYWRtaW5AdGhlY2xvY2tjaGFpbi5pbyIsImFjdGlvbiI6InRva2VuLWFwaSIsImlhdCI6MTcxNjYyODAxNn0.fqvsFR8PwDKVTV9ictvrtGFYC4bd8KqGAs37ogoZmbg'
  GEM: 'AIzaSyBU3jaH-UHY_UjJIFKFqtsrsF0PfO60Qkw'
  REDIS_URL: localhost
  REDIS_PORT: 6379




#   POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
#   POSTGRES_DB_USER: ${POSTGRES_DB_USER}
#   POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
#   POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
#   POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
#   PORT: ${PORT}
#   TOKEN_EXPIRATION_TIME: ${TOKEN_EXPIRATION_TIME}
#   NODE_ENV: ${NODE_ENV}
#   TOKEN_SECRET: ${TOKEN_SECRET}
#   REFRESH_TOKEN_EXPIRATION_TIME: ${REFRESH_TOKEN_EXPIRATION_TIME}
#   TERMII_API_KEY: ${TERMII_API_KEY}
#   SERVER_URL: ${SERVER_URL}
#   THROTTLE_LIMIT: ${THROTTLE_LIMIT}
#   THROTTLE_TTL: ${THROTTLE_TTL}
#   CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
#   CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
#   CLOUDINARY_NAME: ${ CLOUDINARY_NAME}
#   DOJAH_SECRET_KEY: ${ DOJAH_SECRET_KEY}
#   DOJAH_APP_ID: ${ DOJAH_APP_ID}
#   FLUTTER_WAVE_SECRET_KEY: ${ FLUTTER_WAVE_SECRET_KEY}
#   FLUTTER_WAVE_ENCRYPTION_SECRET: ${ FLUTTER_WAVE_ENCRYPTION_SECRET}
#   MAIL_GUN_SECRET_KEY: ${ MAIL_GUN_SECRET_KEY}
#   ADMIN_DASHBOARD_URL:  ${ ADMIN_DASHBOARD_URL}
#   FRONTEND_URL:  ${ FRONTEND_URL}
#   FIRE_BLOCK_API_SANDBOX_KEY: ${ FIRE_BLOCK_API_SANDBOX_KEY}
#   FIRE_BLOCK_API_LIVE_KEY: ${ FIRE_BLOCK_API_LIVE_KEY}
#   FIRE_BLOCK_PUB_KEY: ${ FIRE_BLOCK_PUB_KEY}
#   FIRE_BLOCK_BASE_URL: ${ FIRE_BLOCK_BASE_URL}
#   API_ENCRYPT_AND_DECRYPT_KEY:  ${ API_ENCRYPT_AND_DECRYPT_KEY}
#   FIRE_BLOCK_API_SECRET:  ${ FIRE_BLOCK_API_SECRET}
#   IDENTITYPASS_SEC_KEY: ${ IDENTITYPASS_SEC_KEY}
#   IDENTITYPASS_APP_ID:  ${ IDENTITYPASS_APP_ID}
#   TRONSCAN_API_KEY_TOKEN: ${TRONSCAN_API_KEY_TOKEN}
#   OPTIMISM_SEC_KEY: ${OPTIMISM_SEC_KEY}
#   ETHER_SCAN_KEY: ${ETHER_SCAN_KEY}
#   POLYGON_SCAN_KEY: ${POLYGON_SCAN_KEY}
#   BSC_SCAN_KEY: ${BSC_SCAN_KEY}
#   SOL_SCAN_KEY: ${SOL_SCAN_KEY}
#   GEM: ${GEM}
#   REDIS_URL: ${REDIS_URL}
#   REDIS_PORT: ${REDIS_PORT}

