export enum AdminEventEnums {
  ASSIGN_ACCOUNT_NUMBER_EMAIL = 'ASSIGN_ACCOUNT_NUMBER_EMAIL',
  LEVEL_TWO_KYC_EMAIL = 'LEVEL_TWO_KYC_EMAIL',
  ADMIN_WALLET_UPDATE = 'ADMIN_WALLET_UPDATE',
  SEND_REQUEST_ACCESS_MAIL_TO_SA = 'SEND_REQUEST_ACCESS_MAIL_TO_SA',
  SEND_REQUEST_ACCESS_MAIL = 'SEND_REQUEST_ACCESS_MAIL',
  SEND_2FA_VERIFICATION_CODE = 'SEND_2FA_VERIFICATION_CODE',
  LOGIN_ALERT = 'LOGIN_ALERT',
  LOG_ADMIN_ACTIVITY = 'LOG_ADMIN_ACTIVITY',
}
