import { BaseEnvConfig } from '@app/lib/env/enum/env.enum';

// put the env variables for the app here
export const ConfigEnum = {
  ...BaseEnvConfig,
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRATION_TIME: 'REFRESH_TOKEN_EXPIRATION_TIME',
  NODE_ENV: 'NODE_ENV',
  SERVER_URL: 'SERVER_URL',
  THROTTLE_TTL: 'THROTTLE_TTL',
  THROTTLE_LIMIT: 'THROTTLE_LIMIT',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  CLOUDINARY_NAME: 'CLOUDINARY_NAME',
  DOJAH_SECRET_KEY: 'DOJAH_SECRET_KEY',
  DOJAH_APP_ID: 'CLOUDINARY_NAME',
  FLUTTER_WAVE_SECRET_KEY: 'FLUTTER_WAVE_SECRET_KEY',
  FLUTTER_WAVE_ENCRYPTION_SECRET: 'FLUTTER_WAVE_ENCRYPTION_SECRET',
  MAIL_GUN_SECRET_KEY: 'MAIL_GUN_SECRET_KEY',
  ADMIN_DASHBOARD_URL: 'ADMIN_DASHBOARD_URL',
  FIRE_BLOCK_BASE_URL: 'FIRE_BLOCK_BASE_URL',
  FIRE_BLOCK_PUB_KEY: 'FIRE_BLOCK_PUB_KEY',
  FIRE_BLOCK_API_SANDBOX_KEY: 'FIRE_BLOCK_API_SANDBOX_KEY',
  FIRE_BLOCK_API_LIVE_KEY: 'FIRE_BLOCK_API_LIVE_KEY',
};

export enum EnvNodeEnv {
  Local = 'local',
  Development = 'development',
  Production = 'production',
  Testing = 'testing',
}
